### ISSUE TITLE
Can't launch IRB in TTY, no way to kill/sigstop

### ISSUE THREAD

**Issue by Souravgoswami** [ruby/irb#296] opened 2021-09-26 23:07 UTC
## Description
Expected Behaviour: Launch IRB in TTY.

Actual Behaviour: Can't seem to launch IRB in TTY, `CTRL + C`, `CTRL + Z`, or `CTRL + \` won't work.  Needed to change terminal and SIGKILL.

## Result of irb_info
Sorry but if I can't launch IRB, how can I paste the command?
Version:

irb 1.3.5 (2021-04-03)
Ruby: 2.7.3
Ruby Host OS: DragonflyBSD 6

## Terminal Emulator
Default TTY 1 - 7 (No GUI installed on system)

## Setting Files
None, first basic install.

## Edit
Ok, so I can ssh to my Linux system, and run IRB. `irb_info` gives:

```
Ruby version: 2.7.3
IRB version: irb 1.3.5 (2021-04-03)
InputMethod: ReidlineInputMethod with Reline 0.2.7
RUBY_PLATFORM: x86_64-dragonfly6
```

**Comment by Souravgoswami** [comment] 2021-09-26 23:11
Well, if I put --nocolorize, it still doesn't work. If I put `--nomultiline` it works.

**Comment by mrdev023** [comment] 2021-11-18 16:55
Same

**Comment by elfham** [comment] 2021-12-11 13:56
I was also able to reproduce the problem on FreeBSD 13.0.
(Ruby 2.7.4, irb 1.3.7 (2021-08-12), Reline 0.2.7, LANG=C.UTF-8)

It seems to be stuck here:

* `Reline::Core#may_req_ambiguous_char_width`
    * => `Reline::IOGate#cursor_pos`
        * => `Reline::ANSI#cursor_pos`
            * `c = stdin.getc`

According to the following article, FreeBSD console does not respond to escape sequence of the cursor position.

* https://www.reddit.com/r/freebsd/comments/p04iwr/getting_cursor_position_on_freebsd_console/

for example, by remote terminal:

```
$ bash
[admin@freebsd ~]$ printf '\033[6n'; sleep 1; echo
^[[2;1R
[admin@freebsd ~]$ 1R
```

by FreeBSD console:

```
$ bash
[admin@freebsd ~]$ printf '\033[6n'; sleep 1; echo

[admin@freebsd ~]$ 
```

In these situation, it seems that we have to determine ambiguous width and cursor position in some other way.

**Comment by tompng** [comment] 2024-10-08 16:38
Fixed in https://github.com/ruby/reline/pull/750

**Closed by tompng** 2024-10-08 16:38 UTC
Labels: bug
