### ISSUE TITLE
Dozens of extra lines are displayed

### ISSUE THREAD

**Issue by universato** [ruby/irb#248] opened 2021-06-23 05:52 UTC
## Description

> What are your expected behavior and actual behavior of your environment?

### Expected

```rb
Users.joins(:posts).select("users.*, posts.*").each do |user_post|
  p user_post.name
end
```

When I paste the above code, dozens of extra line should not be displayed.

### Actual

When I paste the code, dozens of extra lines will be displayed.

[![Image from Gyazo](https://i.gyazo.com/3de4ea3e6104d393479862ee95476b3d.gif)](https://gyazo.com/3de4ea3e6104d393479862ee95476b3d)

## Result of irb_info

```
irb(main):001:0> irb_info
=> 
Ruby version: 3.0.1
IRB version: irb 1.3.6 (2021-06-19)
InputMethod: ReidlineInputMethod with Reline 0.2.6
RUBY_PLATFORM: x86_64-darwin19
```

## Terminal Emulator

```sh
$ echo $TERM_PROGRAM
vscode

$ code -v
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
```
(macOS Big Sur 11.4 (20F71))

## Setting Files

> Are you using `~/.irbrc` and `~/.inputrc`?

No.

**Comment by aycabta** [comment] 2021-10-03 12:56
Hmm...I can't reproduce it. Would you try it again with the latest version of VSCode and the latest preview version of irb gem by `gem install irb --pre`?

**Comment by universato** [comment] 2022-10-08 06:20
I tried it now with the latest versions, but there are some extra lines

[![Image from Gyazo](https://i.gyazo.com/d5b77e353d984b593f80cf2330d872fe.gif)](https://gyazo.com/d5b77e353d984b593f80cf2330d872fe)

**Comment by tompng** [comment] 2023-04-08 19:48
This is fixed in reline's side https://github.com/ruby/reline/pull/474.
![スクリーンショット 2023-04-09 4 46 25](https://user-images.githubusercontent.com/1780201/230739983-a3cd0801-17ea-4a8c-9299-03a7af2557dd.png)

**Closed by tompng** 2023-04-08 19:48 UTC
