### ISSUE TITLE
History file being overidden if initially empty

### ISSUE THREAD

**Issue by krystof-k** [ruby/irb#388] opened 2022-08-05 17:42 UTC
## Description

I'm running multiple containers via Docker Compose with all of them mapped to a single .irb-history file which is placed on Docker volume. When they are launched, the (last?) one overrides the history.

Consider following example:

- Dockerfile:
  ```dockerfile
  FROM ruby:alpine
  RUN echo "IRB.conf[:HISTORY_FILE] = ENV['IRB_HISTORY_FILE'] if ENV['IRB_HISTORY_FILE']" >> ~/.irbrc
  ```

- docker-compose.yaml:
  ```yaml
  services:
    first:
      build:
        context: .
      volumes:
        - history:/root/.history
      environment:
        HISTFILE: /root/.history/.bash_history
        IRB_HISTORY_FILE: /root/.history/.irb-history
      command: tail -f /dev/null
    second:
      extends:
        service: first
  volumes:
    history:
  ```

- run:
  ```console
  docker compose up -d
  ```

  run in another terminal:
  ```console
  docker compose exec first irb
  puts 'first'
  ```

  run in another terminal:
  ```console
  docker compose exec second irb
  puts 'second'
  ```
  run in first terminal:
  ```console
  docker compose down
  ```

  run in first terminal:
  ```console
  docker compose run first cat /root/.history/.irb-history
  ```

  result:
  ```console
  puts 'second'
  ```

## Result of irb_info

```
irb(main):001:0> irb_info
=> 
Ruby version: 3.1.2                            
IRB version: irb 1.4.1 (2021-12-25)            
InputMethod: ReidlineInputMethod with Reline 0.3.0
.irbrc path: /root/.irbrc                      
RUBY_PLATFORM: aarch64-linux-musl              
LANG env: C.UTF-8                              
East Asian Ambiguous Width: 1 
```

## Setting Files

`~/.irbrc`:

```ruby
IRB.conf[:HISTORY_FILE] = ENV['IRB_HISTORY_FILE'] if ENV['IRB_HISTORY_FILE']
```

**Comment by krystof-k** [comment] 2022-08-05 17:43
I understood that something that should probably handle this was done by @jeremyevans in #193, but it is definitely not working in this case.

**Comment by jeremyevans** [comment] 2022-08-05 17:56
If you can provide steps to reproduce this issue without docker, I will look into it.

**Comment by krystof-k** [comment] 2022-08-05 18:03
I have no idea how. However exactly the same approach for .bash_history is working with no issue.

**Comment by krystof-k** [comment] 2022-08-05 18:41
OK, maybe I did.

First – ensure there is no history file existing.

Launch IRB in two windows, enter someting in the first, exit, enter something in the second, exit. You will have only the history from the second.

**Comment by jeremyevans** [comment] 2022-08-05 18:53
Thank you for that.  I can reproduce the issue.  I'll look into it, and hopefully have a fix today or next week.

**Comment by krystof-k** [comment] 2022-08-05 18:57
Thanks. Unfortunately I'm afraid that this is not the same issue I'm actually facing in the Docker Compose setup with Rails :(

**Comment by jeremyevans** [comment] 2022-08-05 19:11
Can you try this patch?:

```diff
diff --git a/lib/irb/ext/save-history.rb b/lib/irb/ext/save-history.rb
index 7acaebe..fd5db16 100644
--- a/lib/irb/ext/save-history.rb
+++ b/lib/irb/ext/save-history.rb
@@ -81,9 +81,9 @@ module IRB
             end
           }
         end
-        @loaded_history_lines = history.size
-        @loaded_history_mtime = File.mtime(history_file)
       end
+      @loaded_history_lines = history.size
+      nil
     end

     def save_history
@@ -107,21 +107,10 @@ module IRB
           raise
         end

-        if File.exist?(history_file) && @loaded_history_mtime &&
-           File.mtime(history_file) != @loaded_history_mtime
-          history = history[@loaded_history_lines..-1]
-          append_history = true
-        end
+        history = history[@loaded_history_lines..-1]

-        open(history_file, "#{append_history ? 'a' : 'w'}:#{IRB.conf[:LC_MESSAGES].encoding}", 0600) do |f|
+        open(history_file, "a:#{IRB.conf[:LC_MESSAGES].encoding}", 0600) do |f|
           hist = history.map{ |l| l.split("\n").join("\\\n") }
-          unless append_history
-            begin
-              hist = hist.last(num) if hist.size > num and num > 0
-            rescue RangeError # bignum too big to convert into `long'
-              # Do nothing because the bignum should be treated as inifinity
-            end
-          end
           f.puts(hist)
         end
       end
```

**Comment by krystof-k** [comment] 2022-08-05 19:36
Is it enough if I just edit the file in `/usr/local/bundle/gems/irb-1.4.1`?

**Comment by jeremyevans** [comment] 2022-08-05 19:41
That should work.

**Comment by krystof-k** [comment] 2022-08-05 19:53
Yes! That seems to be working (my original issue in Docker Compose no longer occurs).

**Comment by jeremyevans** [comment] 2022-08-05 19:56
OK.  Let me update the tests and send a pull request for this.

**Comment by jeremyevans** [comment] 2022-08-05 20:07
Looks like my previous diff fixed one issue, but broke others.  Here's a much simpler diff that doesn't break any tests:

```diff
diff --git a/lib/irb/ext/save-history.rb b/lib/irb/ext/save-history.rb
index 7acaebe..83d0710 100644
--- a/lib/irb/ext/save-history.rb
+++ b/lib/irb/ext/save-history.rb
@@ -107,7 +107,7 @@ module IRB
           raise
         end

-        if File.exist?(history_file) && @loaded_history_mtime &&
+        if File.exist?(history_file) &&
            File.mtime(history_file) != @loaded_history_mtime
           history = history[@loaded_history_lines..-1]
           append_history = true
```

If there is no history file originally, `@loaded_history_mtime` is not set, but we should still append in that case, as it is obvious the file has changed.

**Comment by jeremyevans** [comment] 2022-08-05 20:37
OK, I submitted #389 to fix this

**Comment by krystof-k** [comment] 2022-08-05 21:15
That seems to be working as well. Awesome, many thanks!

**Closed** 2022-09-14 01:15 UTC
