### ISSUE TITLE
Encoding::ConverterNotFoundError: ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by taketo1113** [ruby/irb#779] opened 2023-11-22 00:11 UTC
## Description

It raises multiple error `Encoding::ConverterNotFoundError` and actual exception of `SQLite3::CantOpenException`.

This repository is an example of reproduction.
https://github.com/taketo1113/irb-test

Error messages:
```
$ bundle exec irb
irb(main):001> require './test.rb'
irb(main):002> Test.new.exec
1
2
3
...
246
247
248
bundler: failed to load command: irb (/Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/bin/irb)
/Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:678:in `initialize': code converter not found (ASCII-8BIT to UTF-8) (Encoding::ConverterNotFoundError)
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:678:in `new'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:678:in `encode_with_invalid_byte_sequence'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:723:in `handle_exception'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:529:in `rescue in block (2 levels) in eval_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:509:in `block (2 levels) in eval_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:823:in `signal_status'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:508:in `block in eval_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:590:in `block in each_top_level_statement'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:585:in `loop'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:585:in `each_top_level_statement'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:507:in `eval_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:494:in `block in run'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:493:in `catch'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:493:in `run'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:395:in `start'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/exe/irb:9:in `<top (required)>'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/bin/irb:25:in `load'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/bin/irb:25:in `<top (required)>'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
	from /Users/taketo/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/taketo/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
/Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/sqlite3-1.6.8-arm64-darwin/lib/sqlite3/database.rb:105:in `open_v2': unable to open database file (SQLite3::CantOpenException)
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/sqlite3-1.6.8-arm64-darwin/lib/sqlite3/database.rb:105:in `initialize'
	from /Users/taketo/irb-test/test.rb:12:in `new'
	from /Users/taketo/irb-test/test.rb:12:in `select'
	from /Users/taketo/irb-test/test.rb:7:in `block in exec'
	from /Users/taketo/irb-test/test.rb:5:in `each'
	from /Users/taketo/irb-test/test.rb:5:in `exec'
	from (irb):2:in `<top (required)>'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb/workspace.rb:117:in `eval'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb/workspace.rb:117:in `evaluate'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb/context.rb:562:in `evaluate'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:515:in `block (2 levels) in eval_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:823:in `signal_status'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:508:in `block in eval_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:590:in `block in each_top_level_statement'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:585:in `loop'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:585:in `each_top_level_statement'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:507:in `eval_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:494:in `block in run'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:493:in `catch'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:493:in `run'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:395:in `start'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/exe/irb:9:in `<top (required)>'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/bin/irb:25:in `load'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/bin/irb:25:in `<top (required)>'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
	from /Users/taketo/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/taketo/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
$
```

## Result of irb_info

```
irb(main):001:0> irb_info
Ruby version: 3.2.2
IRB version: irb 1.9.1 (2023-11-21)
InputMethod: RelineInputMethod with Reline 0.4.0
Completion: Autocomplete, RegexpCompletor
RUBY_PLATFORM: arm64-darwin23
LANG env: ja_JP.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

What's your terminal emulator?
Terminal.app

## Setting Files

Are you using ~/.irbrc and ~/.inputrc?
No

**Comment by tompng** [comment] 2023-11-22 02:11
It seems `Encoding::Converter.new(Encoding::ASCII_8BIT, Encoding::UTF_8)` is raising `code converter not found (ASCII-8BIT to UTF-8) (Encoding::ConverterNotFoundError)` (but cannot reproduce in my environment)

Shorter reproduce code for my environment
```ruby
irb(main):001> raise 'a'.force_encoding(Encoding::MacJapan)
```
```ruby
irb(main):001> raise StandardError.new.tap{def _1.message; raise; end}
```

Similar to #233 that exception occurred inside `def handle_exception`

**Comment by taketo1113** [comment] 2023-11-22 05:29
@tompng Thanks to reply.

It seems to fixed multiple errors by patching the bellow PR in my environment.
but It raises another error `Errno::EMFILE`.
https://github.com/ruby/irb/pull/780
https://github.com/ruby/irb/pull/780/commits/d8ea8e60d92779be15a85f702122d7dced814518

```
...
246
247
248
#<SQLite3::CantOpenException: unable to open database file>
bundler: failed to load command: irb (/Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/bin/irb)
/Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/reline-0.4.0/lib/reline/config.rb:139:in `readlines': Too many open files @ rb_sysopen - /Users/taketo/.inputrc (Errno::EMFILE)
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/reline-0.4.0/lib/reline/config.rb:139:in `read'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/reline-0.4.0/lib/reline.rb:335:in `inner_readline'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/reline-0.4.0/lib/reline.rb:273:in `block in readmultiline'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/reline-0.4.0/lib/reline/ansi.rb:152:in `block in with_raw_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/reline-0.4.0/lib/reline/ansi.rb:152:in `raw'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/reline-0.4.0/lib/reline/ansi.rb:152:in `with_raw_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/reline-0.4.0/lib/reline.rb:269:in `readmultiline'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/forwardable.rb:240:in `readmultiline'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb/input-method.rb:452:in `gets'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:539:in `block in read_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:830:in `signal_status'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:537:in `read_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:559:in `readmultiline'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:586:in `block in each_top_level_statement'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:585:in `loop'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:585:in `each_top_level_statement'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:507:in `eval_input'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:494:in `block in run'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:493:in `catch'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:493:in `run'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/lib/irb.rb:395:in `start'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/gems/irb-1.9.1/exe/irb:9:in `<top (required)>'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/bin/irb:25:in `load'
	from /Users/taketo/irb-test/tmp/bundle/ruby/3.2.0/bin/irb:25:in `<top (required)>'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/taketo/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
	from /Users/taketo/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/taketo/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
```

**Comment by tompng** [comment] 2023-11-22 06:58
I confirmed it with restricting number of file descriptor by ulimit command.
I think `db.close` is missing or ulimit for file descriptors is too strict.

It's hard to avoid `Too many open files` when you are really opening too many files without closing it and reached the resource limit. In such case, I think system getting unresponsive is not wrong.


It's not just for reading `.inputrc`. IRB opens some files(ruby script, rdoc document, etc) lazily and it all fails.

**Comment by tompng** [comment] 2023-11-22 13:54
Normally, `Encoding::Converter.new(Encoding::ASCII_8BIT, Encoding::UTF_8)` does not raise error.
In this case, loading converter failed because of too many open files.

```ruby
# Save as test.rb and run with `ruby test.rb`
files = []
begin
  (1..300).each do |i|
    file = File.open('./test.rb', 'r')
    files << file
  end
  puts 'to reproduce, restrict file descriptor num by `ulimit -n 256`'
rescue # Errno::EMFILE
  # Can't open any files now
  # Encoding::Converter.new(Encoding::ASCII_8BIT, Encoding::UTF_8) # Encoding::ConverterNotFoundError
  files.each(&:close)
  # Now, files can be opened
  p Encoding::Converter.new(Encoding::ASCII_8BIT, Encoding::UTF_8) # this succeeds
end
```

**Comment by taketo1113** [comment] 2023-11-22 15:09
I got it.

I think there is no problem.
> but It raises another error Errno::EMFILE.

**Closed** 2023-11-24 16:11 UTC
